CREATE TABLE PESSOA
        (
            CPF CHAR(11) NOT NULL UNIQUE,
            NOME VARCHAR(15) NOT NULL,
            NOME_DO_MEIO VARCHAR(15),
            ULTIMO_NOME VARCHAR(15) NOT NULL,
            ENDERECO  VARCHAR NOT NULL,
            CIDADE VARCHAR NOT NULL,
            ESTADO VARCHAR(2) NOT NULL,
            CEP INT NOT NULL,
            DATA_DE_NASCIMENTO DATE
        );
        
CREATE TABLE FUNCIONARIO 
    (
        SALARIO DECIMAL(10,2) NOT NULL,
        MATRICULA VARCHAR NOT NULL,
        /* DIFERENCIAR (ATLETA (A), FUNCIONARIO (F), PRESTADOR DE SERVIÇO (P), TECNICO (T), SOCIO (S) E DIREÇÃO (D))*/
        CPF CHAR(11) NOT NULL UNIQUE,
        NOME VARCHAR(15) NOT NULL,
        NOME_DO_MEIO VARCHAR(15),
        ULTIMO_NOME VARCHAR(15) NOT NULL,
        ENDERECO  VARCHAR NOT NULL,
        CIDADE VARCHAR NOT NULL,
        ESTADO VARCHAR(2) NOT NULL,
        CEP INT NOT NULL,
        DATA_DE_NASCIMENTO DATE,
        PRIMARY KEY (MATRICULA),
        FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
        FOREIGN KEY (NOME) REFERENCES PESSOA (NOME),
        FOREIGN KEY (NOME_DO_MEIO) REFERENCES PESSOA (NOME_DO_MEIO),
        FOREIGN KEY (ULTIMO_NOME) REFERENCES PESSOA (ULTIMO_NOME),
        FOREIGN KEY (ENDERECO) REFERENCES PESSOA (ENDERECO),
        FOREIGN KEY (CIDADE) REFERENCES PESSOA (CIDADE),
        FOREIGN KEY (ESTADO) REFERENCES PESSOA (ESTADO),
        FOREIGN KEY (CEP) REFERENCES PESSOA (CEP),
        FOREIGN KEY (DATA_DE_NASCIMENTO) REFERENCES PESSOA (DATA_DE_NASCIMENTO)

    );
CREATE TABLE ATLETA
    (
        CATEGORIA_DE_ATUACAO VARCHAR NOT NULL,
        SALDO_DE_CESTAS INT NOT NULL,
        SALDO_DE_DERROTA INT NOT NULL,
        SALARIO DECIMAL(10,2) NOT NULL,
        MATRICULA VARCHAR NOT NULL,
        CPF CHAR(11) NOT NULL UNIQUE,
        NOME VARCHAR(15) NOT NULL,
        NOME_DO_MEIO VARCHAR(15),
        ULTIMO_NOME VARCHAR(15) NOT NULL,
        ENDERECO  VARCHAR NOT NULL,
        CIDADE VARCHAR NOT NULL,
        ESTADO VARCHAR(2) NOT NULL,
        CEP INT NOT NULL,
        DATA_DE_NASCIMENTO DATE,
        PRIMARY KEY (MATRICULA),
        FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
        FOREIGN KEY (NOME) REFERENCES PESSOA (NOME),
        FOREIGN KEY (NOME_DO_MEIO) REFERENCES PESSOA (NOME_DO_MEIO),
        FOREIGN KEY (ULTIMO_NOME) REFERENCES PESSOA (ULTIMO_NOME),
        FOREIGN KEY (ENDERECO) REFERENCES PESSOA (ENDERECO),
        FOREIGN KEY (CIDADE) REFERENCES PESSOA (CIDADE),
        FOREIGN KEY (ESTADO) REFERENCES PESSOA (ESTADO),
        FOREIGN KEY (CEP) REFERENCES PESSOA (CEP),
        FOREIGN KEY (DATA_DE_NASCIMENTO) REFERENCES PESSOA (DATA_DE_NASCIMENTO),
        FOREIGN KEY (SALARIO) REFERENCES FUNCIONARIO (SALARIO),
        FOREIGN KEY (MATRICULA) REFERENCES FUNCIONARIO (MATRICULA)
    );
CREATE TABLE TECNICO
    (
        CATEGORIA_DE_TREINO VARCHAR NOT NULL,
        SALDO_DE_VITORIA INT NOT NULL,
        SALDO_DE_DERROTA INT NOT NULL,
        SALARIO DECIMAL(10,2) NOT NULL,
        MATRICULA VARCHAR NOT NULL,
        CPF CHAR(11) NOT NULL UNIQUE,
        NOME VARCHAR(15) NOT NULL,
        NOME_DO_MEIO VARCHAR(15),
        ULTIMO_NOME VARCHAR(15) NOT NULL,
        ENDERECO  VARCHAR NOT NULL,
        CIDADE VARCHAR NOT NULL,
        ESTADO VARCHAR(2) NOT NULL,
        CEP INT NOT NULL,
        DATA_DE_NASCIMENTO DATE,
        PRIMARY KEY (MATRICULA),
        FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
        FOREIGN KEY (NOME) REFERENCES PESSOA (NOME),
        FOREIGN KEY (NOME_DO_MEIO) REFERENCES PESSOA (NOME_DO_MEIO),
        FOREIGN KEY (ULTIMO_NOME) REFERENCES PESSOA (ULTIMO_NOME),
        FOREIGN KEY (ENDERECO) REFERENCES PESSOA (ENDERECO),
        FOREIGN KEY (CIDADE) REFERENCES PESSOA (CIDADE),
        FOREIGN KEY (ESTADO) REFERENCES PESSOA (ESTADO),
        FOREIGN KEY (CEP) REFERENCES PESSOA (CEP),
        FOREIGN KEY (DATA_DE_NASCIMENTO) REFERENCES PESSOA (DATA_DE_NASCIMENTO),
        FOREIGN KEY (SALARIO) REFERENCES FUNCIONARIO (SALARIO),
        FOREIGN KEY (MATRICULA) REFERENCES FUNCIONARIO (MATRICULA)
    );
CREATE TABLE SOCIOS 
    (
        MATRICULA VARCHAR(10) UNIQUE NOT NULL, 
        NOME VARCHAR(15) NOT NULL, 
        NOME_DO_MEIO VARCHAR(15), 
        ULTIMO_NOME VARCHAR(15) NOT NULL, 
        CPF VARCHAR(11) UNIQUE NOT NULL,
        ENDERECO VARCHAR(45), 
        DATA_DE_NASC DATE, 
        ATIVIDADES_MATRICULADO VARCHAR(100),
        PRIMARY KEY(MATRICULA),
        FOREIGN KEY(CPF, NOME, NOME_DO_MEIO, ULTIMO_NOME, DATA_DE_NASC, ENDERECO) REFERENCES PESSOA(CPF, NOME, NOME_DO_MEIO, ULTIMO_NOME, DATA_DE_NASC, ENDERECO)
    );

CREATE TABLE PARTIDA 
    (
        ID_DA_PARTIDA VARCHAR(8) UNIQUE NOT NULL,
        CESTAS_RECEBIDAS SMALLINT,
        CESTAS_FEITAS SMALLINT,
        FALTAS SMALLINT,
        TIME_ESCALADO VARCHAR(350) NOT NULL,
        DIA_DA_PARTIDA DATE NOT NULL,
        PRIMARY KEY(ID_DA_PARTIDA)
    );

CREATE TABLE CAMPEONATO
    (
        NOME_DO_CAMPEONATO VARCHAR(30) UNIQUE NOT NULL,
        TIME_TITULAR VARCHAR(350) NOT NULL,
        CESTAS_FEITAS SMALLINT,
        CESTAS_RECEBIDAS TINYINT,
        FALTAS SMALLINT,
        TREINADOR VARCHAR(35) NOT NULL,
        PRIMARY KEY(NOME_DO_CAMPEONATO)
    );
CREATE TABLE DEPARTAMENTOS
    (
        DIRETOR CHAR(15),
        NOME_DE_DEPARTAMENTO VARCHAR(15) NOT NULL,
        NUMERO_FUNCIONARIOS INT,
        ORCAMENTO FLOAT NOT NULL,
        PRIMARY KEY (NOME_DE_DEPARTAMENTO)
    );
CREATE TABLE ATIVIDADES
    (
        LOCAL VARCHAR(15) NOT NULL,   
        ALUNO VARCHAR (15) INT,
        PROFESSOR VARCHAR (15),
        HORA TIME (0) NOT NULL,
        CODIGO CHAR(10) UNIQUE NOT NULL, 
        PRIMARY KEY (CODIGO)
    );
CREATE TABLE DIRECAO
    ( 
      MATRICULA VARCHAR NOT NULL,
      PRESIDENTE VARCHAR(15) NOT NULL,
      MANDATO VARCHAR(15) NOT NULL,
      DATA_DE_MANDATO VARCHAR(15) NOT NULL,
      MEMBROS VARCHAR   NOT NULL,
      CPF CHAR(11) NOT NULL UNIQUE,
      NOME VARCHAR(15) NOT NULL,
      NOME_DO_MEIO VARCHAR(15),
      ULTIMO_NOME VARCHAR(15) NOT NULL,
      DATA_DE_NASCIMENTO DATE,
      PRIMARY KEY (MATRICULA),
      FOREIGN KEY (MEMBROS) REFERENCES DEPARTAMENTOS (DIRECAO)
    );   
   
CREATE TABLE PRESTADOR_DE_SERVICO
    (   
      SERVICO_PRESTADO VARCHAR NOT NULL,
      DATA_DA_PARTIDA VARCHAR(15) NOT NULL,
      CODIGO VARCHAR NOT NULL,
      CPF CHAR(11) NOT NULL UNIQUE,
      PRESTA_SERVICO VARCHAR NOT NULL
    );  
