CREATE TABLE SOCIOS(
  MATRICULA CHAR(10) UNIQUE NOT NULL, 
  PRIMEIRO_NOME VARCHAR(15) NOT NULL, 
  NOME_DO_MEIO VARCHAR(45), 
  ULTIMO_NOME VARCHAR(15) NOT NULL, 
  CPF CHAR(11) UNIQUE NOT NULL,
  ENDERECO VARCHAR(45), 
  DATA_DE_NASC DATE, 
  ATIVIDADES_MATRICULADO VARCHAR(100),
  PRIMARY KEY(MATRICULA)
  );
