CREATE DATABASE EMPRESA; 
    CREATE TABLE FUNCIONARIO
        (PNOME VARCHAR(15) NOT NULL, 
        NOMEDOMEIO VARCHAR(15),
        UNOME VARCHAR(15) NOT NULL,
        DATADENASC DATE NOT NULL,
        CPF CHAR NOT NULL UNIQUE,
        SEXO CHAR, 
        ENDERECO VARCHAR(50), 
        SALARIO FLOAT NOT NULL, 
        PRIMARY KEY(CPF)); 
    CREATE TABLE DEPARTAMENTO
        (NOME_DEPARTAMENTO VARCHAR(15) NOT NULL,
         NUMERO_DEPARTAMENTE INT NOT NULL,);
